#!/usr/bin/env bash

docker run -d --name deluge-vpn \
	--cap-add=NET_ADMIN \
	--network=edgarnet \
	-p 8112:8112 \
	-p 8118:8118 \
	-p 58846:58846 \
	-p 58946:58946 \
	-v /mnt/KodiDrive/deluge/data:/data \
	-v /mnt/KodiDrive/deluge/config:/config \
	-v /etc/localtime:/etc/localtime:ro \
	-e VPN_ENABLED=yes \
	-e VPN_USER=p4877007 \
	-e VPN_PASS=LWZHxwR9fG \
	-e VPN_PROV=pia \
	-e STRICT_PORT_FORWARD=yes \
	-e ENABLE_PRIVOXY=yes \
	-e LAN_NETWORK=172.22.0.0/16 \
	-e NAME_SERVERS=209.222.18.222 \
	-e DELUGE_DAEMON_LOG_LEVEL=error \
	-e DELUGE_WEB_LOG_LEVEL=error \
	-e DEBUG=false \
	-e UMASK=002 \
	-e PUID=1000 \
	-e PGID=1002 \
	binhex/arch-delugevpn 
