#!/usr/bin/env bash

docker run -d --name=sabnzbd \
	--net=container:transmission_openvpn \
	-e PUID=1000 \
	-e PGID=1002 \
	-e TZ=America/Chicago \
	-v /mnt/KodiDrive/sabnzbd:/config \
	-v /mnt/KodiDrive/completed:/downloads \
	-v /mnt/KodiDrive/incomplete:/incomplete-downloads \
	--restart unless-stopped \
	linuxserver/sabnzbd
