#!/usr/bin/env bash

docker run -d --name=tautulli \
	-e PUID=972 \
	-e PGID=972 \
	-e TZ=America/Chicago \
	-p 8181:8181 \
	-v /mnt/KodiDrive/tautulli:/config \
	-v /var/lib/plex/'Plex Media Server'/Logs:/logs \
	--restart unless-stopped \
	linuxserver/tautulli
